ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER PRG2_APP IDENTIFIED BY prg2_2026;

GRANT CREATE SESSION TO PRG2_APP;
GRANT CREATE TABLE TO PRG2_APP;
GRANT CREATE SEQUENCE TO PRG2_APP;
GRANT CREATE VIEW TO PRG2_APP;
GRANT CREATE PROCEDURE TO PRG2_APP;

ALTER USER PRG2_APP QUOTA UNLIMITED ON USERS;
