CREATE TABLE prg2_usuarios (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario VARCHAR2(40) UNIQUE NOT NULL,
  clave_hash VARCHAR2(64) NOT NULL,
  nombre VARCHAR2(120) NOT NULL,
  rol VARCHAR2(30) DEFAULT 'ADMIN' NOT NULL,
  activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S', 'N'))
);

CREATE TABLE prg2_alumnos (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(120) NOT NULL,
  documento VARCHAR2(30) UNIQUE NOT NULL,
  email VARCHAR2(120),
  telefono VARCHAR2(40),
  fecha_alta DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE prg2_materias (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(120) NOT NULL,
  codigo VARCHAR2(20) UNIQUE NOT NULL,
  creditos NUMBER(3) DEFAULT 0 NOT NULL
);

CREATE TABLE prg2_inscripciones (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id NUMBER NOT NULL REFERENCES prg2_alumnos(id) ON DELETE CASCADE,
  materia_id NUMBER NOT NULL REFERENCES prg2_materias(id) ON DELETE CASCADE,
  estado VARCHAR2(20) DEFAULT 'CURSANDO' CHECK (estado IN ('CURSANDO', 'APROBADO', 'REPROBADO')),
  nota NUMBER(4,2),
  fecha DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_prg2_inscripcion UNIQUE (alumno_id, materia_id)
);

INSERT INTO prg2_usuarios (usuario, clave_hash, nombre, rol)
VALUES ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Administrador PRG2', 'ADMIN');

INSERT INTO prg2_alumnos (nombre, documento, email, telefono)
VALUES ('Ana Benitez', '5123456', 'ana.benitez@mail.com', '0981 111222');

INSERT INTO prg2_alumnos (nombre, documento, email, telefono)
VALUES ('Luis Ferreira', '4987654', 'luis.ferreira@mail.com', '0982 333444');

INSERT INTO prg2_alumnos (nombre, documento, email, telefono)
VALUES ('Maria Duarte', '5456789', 'maria.duarte@mail.com', '0983 555666');

INSERT INTO prg2_materias (nombre, codigo, creditos)
VALUES ('Programacion 2', 'PRG2', 6);

INSERT INTO prg2_materias (nombre, codigo, creditos)
VALUES ('Base de Datos', 'BD1', 5);

INSERT INTO prg2_materias (nombre, codigo, creditos)
VALUES ('Ingenieria de Software', 'IS1', 4);

INSERT INTO prg2_inscripciones (alumno_id, materia_id, estado, nota)
VALUES (1, 1, 'APROBADO', 4.50);

INSERT INTO prg2_inscripciones (alumno_id, materia_id, estado, nota)
VALUES (1, 2, 'CURSANDO', NULL);

INSERT INTO prg2_inscripciones (alumno_id, materia_id, estado, nota)
VALUES (2, 1, 'REPROBADO', 1.80);

INSERT INTO prg2_inscripciones (alumno_id, materia_id, estado, nota)
VALUES (3, 3, 'APROBADO', 5.00);

COMMIT;
